// app/layouts/main/Personal.vue
<script setup lang="ts">

</script>

<template>
  <div class="personal">
    <div class="avatar">
      <img src="/avatar.png" alt="Twisuki"/>
    </div>
    <div class="content">
      <div class="content__1">大家好这里是</div>
      <div class="content__2">Twisuki ~</div>
    </div>
  </div>
</template>

<style scoped>
.personal {
  height: 8rem;
  background-color: #ffaa00;
  display: flex;
  gap: 1rem;
}

.avatar {
  width: 8rem;
  height: 8rem;
  display: flex;
  justify-content: center;
  align-items: center;
}

.avatar img {
  width: 6rem;
  height: 6rem;
  border-radius: 50%;
}

.content {
  padding-right: 2rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
}

.content__1 {
  font-size: 1.75rem;
}

.content__2 {
  font-size: 2rem;
}
</style>

// src/components/main/Personal.tsx
import Image from "next/image";


export default function Personal() {
  return (
    <div className="w-72 h-36 bg-blue-600 flex-col justify-center items-center">
      <div className="w-72 h-24 flex justify-center items-center gap-4">
        <Image
          src="/avatar.png"
          alt="Twisuki"
          width="400"
          height="400"
          className="w-18 h-18 rounded-full object-cover"
        />
        <div className="text-white text-3xl">
          Nya_Twisuki
        </div>
      </div>
      <div className="w-full h-12 text-white text-xl flex justify-center">
        大家好这里是Twisuki~
      </div>
    </div>
  );
}
